name: "L3: Message Integrity Schema Validation"

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  schema-validation:
    name: "Schema Integrity Test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Layer 3 - Missing Mandatory Field (Empty Body)
        # Expected: 400 Bad Request
        # opcNumber is required in the schema.
        continue-on-error: true
        run: |
          echo "Scenario: Sending an empty JSON object {}"
          PAYLOAD='{}'

          curl -k -v -i \
            --cert ./certs/client.pem --key ./certs/client.key \
            -H "Content-Type: application/json" \
            -w "\nHTTP_STATUS:%{http_code}\n" \
            -d "$PAYLOAD" https://api.eis-poc-gateway.com/api/
                    
      - name: Layer 3 - Invalid Pattern (Regex Check)
        # Expected: 400 Bad Request
        # The regex is ^[A-Z0-9]+$. We send a hyphen '-' to trigger a block.
        continue-on-error: true
        run: |
          echo "Scenario: Sending opcNumber with invalid characters (A123-456)"
          PAYLOAD='{"opcNumber": "A123-456"}'
          
          curl -k -v -s \
            --cert ./certs/client.pem --key ./certs/client.key \
            -H "Content-Type: application/json" \
            -w "\nHTTP_STATUS:%{http_code}\n" \
            -d "$PAYLOAD" https://api.eis-poc-gateway.com/api/mtoapi

      - name: Layer 3 - Undefined Fields (Strict Mode)
        # Expected: 400 Bad Request
        # additionalProperties: false is set in the schema.
        continue-on-error: true
        run: |
          echo "Scenario: Sending valid opcNumber with an extra 'hack' field."
          PAYLOAD='{"opcNumber": "A123456789", "hack": "true"}'
          
          curl -k -v -s \
            --cert ./certs/client.pem --key ./certs/client.key \
            -H "Content-Type: application/json" \
            -w "\nHTTP_STATUS:%{http_code}\n" \
            -d "$PAYLOAD" https://api.eis-poc-gateway.com/api/mtoapi

      - name: Layer 3 - Success Path (Valid Payload)
        # Expected: 200 OK
        run: |
          echo "Scenario: Sending a perfectly valid request (A123456789)"
          PAYLOAD='{"opcNumber": "B98765432109"}'
          
          curl -k -v -s \
            --cert ./certs/client.pem --key ./certs/client.key \
            -H "Content-Type: application/json" \
            -w "\nHTTP_STATUS:%{http_code}\n" \
            -d "$PAYLOAD" https://api.eis-poc-gateway.com/api/mtoapi
