name: "L2: Traffic Protection (Rate Limiting / SLA)"

on:
  workflow_dispatch: # Allows manual trigger from the Actions tab
  push:
    branches: [ main ]

jobs:
  connectivity-test:
    name: Traffic Protection (Rate Limiting / SLA)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Layer 2 - Rate Limiting (regular client)
        continue-on-error: true
        run: |
            # --- Configuration ---
            URL="https://api.eis-poc-gateway.com/api/mtoapi"
            CERT_PATH="./certs/client.pem"
            KEY_PATH="./certs/client.key"
            TOKEN_URL="https://poc-jwt-provider-zm63hj.9d3fd9-1.can-c1.cloudhub.io/token2"
            REQULAR_CLIENT_ID = "fd6a16c7a11d48038f1bc3147a0982a8"
            
            echo "--------------------------------------------------"
            echo "   DEMO: LAYER 2 - Rate Limiting (regular client)        "
            echo "--------------------------------------------------"
                   
            TOKEN=$(curl -s "$TOKEN_URL")
            echo "Request Header:"
            echo "Authorization: Bearer $TOKEN"
             echo "client-id: $REGULAR_CLIENT_ID"
            
            RAW_OUTPUT=$(curl -k -i -s \
                --cert "$CERT_PATH" --key "$KEY_PATH" \
                -H "Authorization: Bearer $TOKEN" \
                -H "Content-Type: application/json" \
                -H "client-id: $REGULAR_CLIENT_ID" \
                -d '{"opcNumber": "B98765432109"}' \
                -w "\nHTTP_STATUS:%{http_code}" \
                "$URL")
            
            STATUS=$(echo "$RAW_OUTPUT" | grep "HTTP_STATUS:" | cut -d':' -f2)
            BODY=$(echo "$RAW_OUTPUT" | sed '/HTTP_STATUS:/d' | sed '1,/^\r\{0,1\}$/d')
            
            if [ "$STATUS" -eq 200 ]; then
                echo "SUCCESS: Request accepted (200 OK)."
            else
                echo "FAILURE: Request returned $STATUS."
            fi
            
            echo "--------------------------------------------------"
            echo "RESPONSE:"
            echo "$BODY"
            echo "--------------------------------------------------"

      - name: Layer 1 - JWT Validation (valid token)
        continue-on-error: true
        run: |
            # --- Configuration ---
            URL="https://api.eis-poc-gateway.com/api/mtoapi"
            CERT_PATH="./certs/client.pem"
            KEY_PATH="./certs/client.key"
            TOKEN_URL="https://poc-jwt-provider-zm63hj.9d3fd9-1.can-c1.cloudhub.io/token2"
            PREMIUM_CLIENT_ID = "fd6a16c7a11d48038f1bc3147a0982a8"
            
            echo "--------------------------------------------------"
            echo "   DEMO: LAYER 1 - IDENTITY CONTROL (JWT VALIDATION)        "
            echo "--------------------------------------------------"
            
            TOKEN=$(curl -s "$TOKEN_URL")
            echo "Request Header:"
            echo "Authorization: Bearer $TOKEN"
            echo "client-id: $PREMIUM_CLIENT_ID"
            
            RAW_OUTPUT=$(curl -k -i -s \
                --cert "$CERT_PATH" --key "$KEY_PATH" \
                -H "Authorization: Bearer $TOKEN" \
                -H "Content-Type: application/json" \
                -H "client-id: $PREMIUM_CLIENT_ID" \
                -d '{"opcNumber": "B98765432109"}' \
                -w "\nHTTP_STATUS:%{http_code}" \
                "$URL")
            
            STATUS=$(echo "$RAW_OUTPUT" | grep "HTTP_STATUS:" | cut -d':' -f2)
            BODY=$(echo "$RAW_OUTPUT" | sed '/HTTP_STATUS:/d' | sed '1,/^\r\{0,1\}$/d')
            
            if [ "$STATUS" -eq 200 ]; then
                echo "SUCCESS: Request accepted (200 OK)."
            else
                echo "FAILURE: Request returned $STATUS."
            fi
            
            echo "--------------------------------------------------"
            echo "RESPONSE:"
            echo "$BODY"
            echo "--------------------------------------------------"    
